# Generated by Django 4.2.7 on 2024-01-31 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('cert_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('cert', models.TextField()),
                ('certificate_type', models.CharField(choices=[('root', 'root'), ('intermediate', 'intermediate'), ('leaf', 'leaf')], max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_revoked', models.BooleanField(default=False)),
                ('received_on', models.DateTimeField()),
                ('confirmed_on', models.DateTimeField()),
                ('superior_cert', models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='non_repudiation.certificate')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_text', models.TextField()),
                ('created_on', models.DateTimeField()),
                ('signature', models.BinaryField()),
                ('certificate_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='non_repudiation.certificate')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=128)),
                ('hash_function', models.CharField(choices=[('SHA256', 'SHA256'), ('SHA512', 'SHA512'), ('SHA3-256', 'SHA3-256'), ('SHA3-512', 'SHA3-512')], max_length=15)),
                ('created_on', models.DateTimeField()),
                ('signature', models.BinaryField()),
                ('document_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='non_repudiation.document')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=40)),
                ('certificate_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='non_repudiation.certificate')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='non_repudiation.organization'),
        ),
    ]
