# Generated by Django 4.2.7 on 2024-03-30 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('non_repudiation', '0003_organization_certificates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='cert_id',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='confirmed_on',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='superior_cert',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='certificates',
        ),
        migrations.AddField(
            model_name='certificate',
            name='cert_digest',
            field=models.CharField(default='123456789ABCDEF', max_length=64, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificate',
            name='organization',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='non_repudiation.organization'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_type',
            field=models.CharField(choices=[('root', 'root'), ('intermediate', 'intermediate'), ('client', 'client')], max_length=20),
        ),
    ]
