# Generated by Django 4.2.7 on 2024-04-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('non_repudiation', '0004_remove_certificate_cert_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_id',
            field=models.CharField(default='docdoc'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('graph', 'graph'), ('domain_specific', 'domain_specific'), ('backbone', 'backbone')], default='graph', max_length=20),
            preserve_default=False,
        ),
    ]
