# Generated by Django 4.2.7 on 2024-04-01 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('non_repudiation', '0005_document_document_id_document_document_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='certificate_id',
            new_name='certificate',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='organization_id',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='token',
            old_name='document_id',
            new_name='document',
        ),
    ]
