# Generated by Django 4.2.7 on 2024-04-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('non_repudiation', '0006_rename_certificate_id_document_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='cert_digest',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_name',
            field=models.CharField(max_length=40, primary_key=True, serialize=False, unique=True),
        ),
    ]
